name: AMS FOD SAST via PAT
 
on: 
  push:
    branches: [main]
  #pull_request:
    # The branches below must be a subset of the branches above
    #branches: [main]
  workflow_dispatch:
jobs:
  FoD-SAST-Scan:
    # Use the appropriate runner for building your source code. 
    # Use Windows runner for projects that use msbuild. Additional changes to RUN commands will be required..
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v4  
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Run FoD SAST Scan
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FODAMS_TENANT}}
          FOD_USER: ${{secrets.FODAMS_USER}}
          FOD_PASSWORD: ${{secrets.FODAMS_PAT}}
          # EXTRA_FOD_LOGIN_OPTS: --socket-timeout=60s
          FOD_RELEASE: 1360993
          EXTRA_PACKAGE_OPTS: -bt none 
          DO_WAIT: true
          DO_EXPORT: true
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
